apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: agora-project-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
